### PR TITLE
HiZ crash fixes and Optick improvements

### LINKED ISSUE #970: VK Out of memory on MacBook Pro M1
Running on MacBook Pro M1 (16Gb) - compiled using Xcode from latest.
Copied base dir over from GOG version and then copied the base folder in GitHub over that.

All is good until starting a new campaign. The first map loads but then I hit an out of memory error with Vulkan. I can dig into it more but first wanted to know if this is unexpected. Also, am I missing a step somewhere? I seem to be missing env maps but I didn't see them in the download from moddb - I don't think that would cause the error though.

Tail of the output looks like:

```
151 warnings
  3267 msec to load game/mars_city1
Sending networkSync cvars:
pm_staminathreshold = 4
pm_noclipspeed = 300
pm_runspeed = 275
pm_walkspeed = 175
pm_crouchspeed = 100
Execution of the command buffer was aborted due to an error during execution. Caused GPU Address Fault Error (0000000b:kIOGPUCommandBufferCallbackErrorPageFault)
[mvk-error] VK_ERROR_OUT_OF_DEVICE_MEMORY: MTLCommandBuffer "vkQueueSubmit MTLCommandBuffer on Queue 0-0" execution failed (code 3): Caused GPU Address Fault Error (0000000b:kIOGPUCommandBufferCallbackErrorPageFault)
libc++abi: terminating due to uncaught exception of type vk::DeviceLostError: vk::Device::getSemaphoreCounterValue: ErrorDeviceLost
Message from debugger: killed
Program ended with exit code: 9
```

Full log is as follows (I removed some repetitive lines ... and noted where).

```
QA Timing INIT: 000779ms
RBDOOM 3 BFG 1.6.0.1403 osx-aarch64 Jan 16 2025 22:45:13
loopback
192.168.1.238/255.255.255.0
no 'base' directory in exe path /Users/ian/doom/RBDOOM-3-BFG/xcode-release/Release/RBDoom3BFG.app/Contents/MacOS, skipping
------ Initializing File System ------
Loaded resource file _common.resources

< removed lines >

file system initialized.
--------------------------------------
WARNING: Unable to open resource file maps/_startup.resources
WARNING: Unable to open resource file maps/_startup.resources
----- Initializing Decls -----
------------------------------
Couldn't open journal files
CPU processors: 10
CPU logical cores: 10
execing default.cfg
execing D3BFGConfig.cfg
couldn't exec autoexec.cfg
----- R_InitOpenGL -----
Initializing Vulkan subsystem
Enabled Vulkan instance extensions:
    VK_EXT_metal_surface
    VK_KHR_surface
    VK_EXT_debug_report
    VK_KHR_get_physical_device_properties2
Enabled Vulkan layers:
Disabled MoltenVK's synchronous queue submits...
Enabled MoltenVK's Metal argument buffers...
Enabled Vulkan device extensions:
    VK_EXT_memory_budget
    VK_EXT_descriptor_indexing
    VK_EXT_debug_marker
    VK_KHR_synchronization2
    VK_KHR_buffer_device_address
    VK_KHR_portability_subset
    VK_KHR_maintenance1
    VK_KHR_swapchain
Created Vulkan device: Apple M1 Pro
----- Initializing Render Shaders -----
Loading shader program builtin/gui
Loading shader program builtin/color
Loading shader program builtin/color
Loading shader program builtin/vertex_color

< removed some lines >

sound system initialized.
--------------------------------------
------- Initializing renderSystem --------
renderSystem initialized.
--------------------------------------
Skipping Intro Videos!
Reading strings/english.lang as UTF-8
9104 strings read
--------- Initializing Game ----------
gamename: baseDOOM-1
gamedate: Jan 16 2025
WARNING: file def/_tb_models.def, line 5230: entityDef 'genmodel_mapobjects_monitors_hangingmonitor' previously defined at def/_tb_models.def:5216
Initializing event system
...543 event definitions
Initializing class hierarchy
...159 classes, 1016496 bytes for event callbacks
Initializing scripts
couldn't read systclbyname
measured CPU frequency: 1001.06 MHz
Compiled 'script/doom_main.script': 3043879662 ms
---------- Compile stats ----------

Memory usage:
     Strings: 120, 15840 bytes
  Statements: 95386, 3052352 bytes
   Functions: 3070, 496728 bytes
   Variables: 239712 bytes
    Mem used: 5818032 bytes
 Static data: 5811160 bytes
   Allocated: 8111952 bytes
 Thread size: 14064 bytes

...6 aas types
game initialized.
--------------------------------------
OpenAL Error: Invalid Enum (0xa002), @ /Users/ian/doom/RBDOOM-3-BFG/neo/sound/OpenAL/AL_SoundSample.cpp 631
WARNING: Couldn't load image: } : }#__0200
Loaded Bink file: 'video/intro/introloop.bik', looping=1, 512x512, 30.00 FPS, 12.0 sec
Loaded Bink file: 'video/mars1.bik', looping=0, 512x512, 30.00 FPS, 32.2 sec
Loaded Bink file: 'video/mars_rotation.bik', looping=1, 1567x406, 30.00 FPS, 100.0 sec
----- idRenderModelManagerLocal::EndLevelLoad -----
    0 models purged from previous level,     3 models kept.
---------------------------------------------------
----- idImageManager::EndLevelLoad -----
WARNING: Couldn't load image: } : }#__0200
WARNING: Couldn't load image: _cinematicY : _cinematicY#__0200
WARNING: Couldn't load image: _cinematicCr : _cinematicCr#__0200
WARNING: Couldn't load image: _cinematicCb : _cinematicCb#__0200
WARNING: Couldn't load image: _cinematic : _cinematic#__0200
WARNING: Couldn't load image: _cinematicY : _cinematicY#__0200
WARNING: Couldn't load image: _cinematicCr : _cinematicCr#__0200
WARNING: Couldn't load image: _cinematicCb : _cinematicCb#__0200
WARNING: Couldn't load image: _cinematic : _cinematic#__0200
WARNING: Couldn't load image: _cinematicY : _cinematicY#__0200
WARNING: Couldn't load image: _cinematicCr : _cinematicCr#__0200
WARNING: Couldn't load image: _cinematicCb : _cinematicCb#__0200
WARNING: Couldn't load image: _cinematic : _cinematic#__0200
   29 images loaded in   0.0 seconds
----------------------------------------
----- idSoundSystemLocal::EndLevelLoad -----
    7 sounds loaded in   0.0 seconds
----------------------------------------
------------- Warnings ---------------
during DOOM 3: BFG Edition initialization...
WARNING: Unable to open resource file maps/_startup.resources
WARNING: file def/_tb_models.def, line 5230: entityDef 'genmodel_mapobjects_monitors_hangingmonitor' previously defined at def/_tb_models.def:5216
WARNING: Couldn't load image: } : }#__0200
WARNING: Couldn't load image: _cinematicY : _cinematicY#__0200
WARNING: Couldn't load image: _cinematicCr : _cinematicCr#__0200
WARNING: Couldn't load image: _cinematicCb : _cinematicCb#__0200
WARNING: Couldn't load image: _cinematic : _cinematic#__0200
7 warnings
Preloading images...
00362 images preloaded ( or were already loaded ) in   0.1 seconds
----------------------------------------
00259 sounds preloaded in   0.1 seconds
----------------------------------------
WARNING: Couldn't load image: _doomclassic : _doomclassic#__0200
WARNING: Couldn't load image: _doomclassic : _doomclassic#__0200
--- Common Initialization Complete ---
QA Timing IIS: 004109ms
WARNING: terminal type 'dumb' is unknown. terminal support may not work correctly
terminal support enabled ( use +set in_tty 0 to disabled )
pid: 44095
ViewBridge to RemoteViewService Terminated: Error Domain=com.apple.ViewBridge Code=18 "(null)" UserInfo={com.apple.ViewBridge.error.hint=this process disconnected remote view controller -- benign unless unexpected, com.apple.ViewBridge.error.description=NSViewBridgeErrorCanceled}
Added local user: Ians-MBP
Opening IP socket: localhost:27015
execing joy_righty.cfg
execing joy_360_0.cfg
NET: PartyToken is 31299 (seed = 94538)
--------- Execute Map Change ---------
Map: game/mars_city1
--------- Game Map Shutdown ----------
--------------------------------------
     1 msec to unload map
    51 msec to free assets
Preloading images...
02180 images preloaded ( or were already loaded ) in   0.4 seconds
----------------------------------------
00305 models preloaded ( or were already loaded ) in   0.1 seconds
----------------------------------------
00551 sounds preloaded in   0.3 seconds
----------------------------------------
Preloading anims...
00630 anims preloaded ( or were already loaded ) in   0.1 seconds
----------------------------------------
----- SetupLightGrid -----

area 0 of 56 (21 x 18 x 5) = 1890 grid points 
area 0 grid size (64 64 128)
area 0 grid bounds (21 18 5)
area 0: 0 of 1890 grid points in empty space (0.00%)

area 1 of 56 (17 x 17 x 55) = 15895 grid points 
area 1 grid size (160 144 208)
area 1 grid bounds (17 17 55)
area 1: 1011 of 15895 grid points in empty space (6.36%)

< removed similar logs >

area 55 of 56 (3 x 3 x 1) = 9 grid points 
area 55 grid size (64 64 128)
area 55 grid bounds (3 3 1)
area 55: 0 of 9 grid points in empty space (0.00%)
----------------------------------
Total valid light grid points 53655
------- Game Map Init SaveGame -------
collision data:
   425 models
 30834 vertices (722 KB)
 54572 edges (1918 KB)
 44488 polygons (3300 KB)
  8144 brushes (1145 KB)
 12573 nodes (589 KB)
 43839 polygon refs (684 KB)
 14455 brush refs (225 KB)
 18344 internal edges
  1463 sharp edges
     0 contained polygons removed
     0 polygons merged
  8587 KB total memory used
9 msec to load collision data.
Preloading collision models...
00183 collision models preloaded ( or were already loaded ) in   0.0 seconds
----------------------------------------
map bounds are (19640.0, 22168.0, 29496.0)
max clip sector is (1227.5, 1385.5, 1843.5)
    2 KB passage memory used to build PVS
    0 msec to calculate PVS
   56 areas
  110 portals
    9 areas visible on average
  448 bytes PVS data
[Load AAS]
loading maps/game/mars_city1.aas48
done.
[Load AAS]
loading maps/game/mars_city1.aas96
[Load AAS]
loading maps/game/mars_city1.aas_guardian
[Load AAS]
loading maps/game/mars_city1.aas_mancubus
[Load AAS]
loading maps/game/mars_city1.aas_sabaoth
[Load AAS]
loading maps/game/mars_city1.aas_cyberdemon
Loaded Bink file: 'sound/vo/video/mfs.bik', looping=0, 256x256, 30.00 FPS, 88.8 sec
Loaded Bink file: 'video/marscity/monoflyby.bik', looping=0, 256x256, 31.25 FPS,  2.7 sec
Loaded Bink file: 'video/marscity/dropship.bik', looping=0, 256x256, 31.25 FPS,  6.8 sec
Loaded Bink file: 'video/marscity/ship.bik', looping=0, 256x256, 30.00 FPS,  4.7 sec
Loaded Bink file: 'video/marscity/decom.bik', looping=1, 128x128, 30.00 FPS,  4.3 sec
Loaded Bink file: 'video/marscity/sci_team_request.bik', looping=0, 256x256, 30.00 FPS,  8.8 sec
Loaded Bink file: 'sound/VO/video/video_ipn_news.bik', looping=0, 256x256, 30.00 FPS, 187.4 sec
Loaded Bink file: 'sound/VO/video/video_marine_sops.bik', looping=0, 256x256, 30.00 FPS, 72.9 sec
Loaded Bink file: 'sound/VO/video/video_plasmagun.bik', looping=0, 256x256, 30.00 FPS, 47.8 sec
Loaded Bink file: 'sound/VO/video/video_uac_welcome.bik', looping=0, 256x256, 30.00 FPS, 80.4 sec
WARNING: marscity_cinematic_sarge_1 has no AAS file
WARNING: marscity_cinematic_sarge2_1 has no AAS file
WARNING: marscity_cinematic_player_sarge has no AAS file
--------------------------------------
----- idRenderModelManagerLocal::EndLevelLoad -----
    0 models purged from previous level,  1037 models kept.
---------------------------------------------------
----- idImageManager::EndLevelLoad -----
WARNING: Couldn't load image: _emptyname : _emptyname#__0200
WARNING: Couldn't load image: env/maps/game/mars_city1/area1_envprobe_1131__1293_75_amb : env/maps/game/mars_city1/area1_envprobe_1131__1293_75_amb#__2105
WARNING: Couldn't load image: env/maps/game/mars_city1/area1_envprobe_1131__1293_75_spec : env/maps/game/mars_city1/area1_envprobe_1131__1293_75_spec#__2105
WARNING: Couldn't load image: env/maps/game/mars_city1/area1_envprobe_1297__1645_49_amb : env/maps/game/mars_city1/area1_envprobe_1297__1645_49_amb#__2105
WARNING: Couldn't load image: env/maps/game/mars_city1/area1_envprobe_1297__1645_49_spec : 

< removed many similar warnings about env maps >

env/maps/game/mars_city1/area55_envprobe__3392__3072_264_amb#__2105
WARNING: Couldn't load image: env/maps/game/mars_city1/area55_envprobe__3392__3072_264_spec : env/maps/game/mars_city1/area55_envprobe__3392__3072_264_spec#__2105
WARNING: Couldn't load image: _cinematicY : _cinematicY#__0200
WARNING: Couldn't load image: _cinematicCr : _cinematicCr#__0200
WARNING: Couldn't load image: _cinematicCb : _cinematicCb#__0200
WARNING: Couldn't load image: _cinematic : _cinematic#__0200
WARNING: Couldn't load image: _cinematicY : _cinematicY#__0200
WARNING: Couldn't load image: _cinematicCr : _cinematicCr#__0200
WARNING: Couldn't load image: _cinematicCb : _cinematicCb#__0200

< removed repeated warnings about cinematic >

 4137 images loaded in   0.7 seconds
----------------------------------------
----- idSoundSystemLocal::EndLevelLoad -----
  160 sounds loaded in   0.2 seconds
----------------------------------------
----- Generating Interactions -----
idRenderWorld::GenerateAllInteractions, msec = 31
interactionTable size: 5871152 bytes
31865 interactions take 2294280 bytes
Used 4667kb of static vertex memory (3%)
Used 3566kb of static index memory (2%)
------------- Warnings ---------------
during game/mars_city1...
WARNING: Couldn't load image: _emptyname : _emptyname#__0200
WARNING: Couldn't load image: env/maps/game/mars_city1/area1_envprobe_1131__1293_75_amb : env/maps/game/mars_city1/area1_envprobe_1131__1293_75_amb#__2105
WARNING: Couldn't load image: env/maps/game/mars_city1/area1_envprobe_1131__1293_75_spec : env/maps/game/mars_city1/area1_envprobe_1131__1293_75_spec#__2105

< removed lots of similar env maps warnings >

WARNING: Couldn't load image: env/maps/game/mars_city1/area55_envprobe__3392__3072_264_spec : env/maps/game/mars_city1/area55_envprobe__3392__3072_264_spec#__2105
WARNING: Couldn't load image: _cinematicY : _cinematicY#__0200
WARNING: Couldn't load image: _cinematicCr : _cinematicCr#__0200
WARNING: Couldn't load image: _cinematicCb : _cinematicCb#__0200
WARNING: Couldn't load image: _cinematic : _cinematic#__0200
151 warnings
  3267 msec to load game/mars_city1
Sending networkSync cvars:
pm_staminathreshold = 4
pm_noclipspeed = 300
pm_runspeed = 275
pm_walkspeed = 175
pm_crouchspeed = 100
Execution of the command buffer was aborted due to an error during execution. Caused GPU Address Fault Error (0000000b:kIOGPUCommandBufferCallbackErrorPageFault)
[mvk-error] VK_ERROR_OUT_OF_DEVICE_MEMORY: MTLCommandBuffer "vkQueueSubmit MTLCommandBuffer on Queue 0-0" execution failed (code 3): Caused GPU Address Fault Error (0000000b:kIOGPUCommandBufferCallbackErrorPageFault)
libc++abi: terminating due to uncaught exception of type vk::DeviceLostError: vk::Device::getSemaphoreCounterValue: ErrorDeviceLost
Message from debugger: killed

```

### PR DESCRIPTION
**Pull request by SRSaunders**
Fixes #970 and fixes/works-aound #940.

This PR solves the following:

1. Apple only - Disables MoltenVK's Metal Argument Buffers feature to prevent crash when HiZ buffer is enabled.
2. Apple only - Improves heuristics for Optick display of MoltenVK's Submit, Image Acquire and Metal Encoding steps.
3. Apple only - Reenables GPU Skinning on Apple Silicon (issue appears to be resolved using current builds, drivers, etc).
4. Linux only - Disables HiZ buffer when running on Intel iGPUs to avoid crash observed with HiZ enabled.  This is possibly a driver issue, and the solution is a workaround.  Downside is that SSR is disabled for Linux + Intel iGPUs.  ~~I would have liked to use your new `R_UseHiZ()` function for this, but instead needed for check for Linux + Intel iGPU at runtime which is easier to do in `DeviceManager_VK::pickPhysicalDevice()`.  I guess `DeviceManager_VK::GetRendererString()` would also work to retrieve the physical device name in `R_UseHiZ()` - I may update TBD.~~ **UPDATED** in additional commit below.
5. All Platfoms - Adds missing Optick GPU events for _Render HiZ_ and _Resolve Screen for SSR_, and now only resolves the screen if **both** `r_useSSR` and `R_UseHiZ()` are enabled (not needed otherwise).

Tested on Win 10, Manjaro Linux, and macOS Ventura (x86_64 & arm64).

### CODE REVIEW

**Comment by SRSaunders** [comment]
@RobertBeckebans I have updated my changes to store the **GPU Vendor** and **Type (discrete, other)** in the glConfig global structure which is general across platforms and rendering APIs.  This allows me to recall the information during rendering and permits logic within `R_UseHiZ(`) to turn HiZ off on Linux when running against Intel iGPU drivers.  Note that my change in `R_UseHiZ()` does not test for Vulkan, since this is implicit on Linux.

File: neo/sys/DeviceManager_DX12.cpp [hunk 1]
```diff
@@ -277,7 +272,9 @@ bool DeviceManager_DX12::CreateDeviceAndSwapChain()
 		}
 		m_RendererString = ss.str();
 
-		isNvidia = IsNvDeviceID( aDesc.VendorId );
+		glConfig.vendor = getGPUVendor( aDesc.VendorId );
+		// SRS - Intel iGPUs typically allocate 128 MB for Dedicated UMA, set threshold at 512 MB to potentially handle other iGPUs (e.g. AMD APUs)
+		glConfig.gpuType = aDesc.DedicatedVideoMemory > 0x20000000 ? GPU_TYPE_DISCRETE : GPU_TYPE_OTHER;
```
Comment (RobertBeckebans) [inline neo/sys/DeviceManager_DX12.cpp:277]: Wether this is a discrete GPU or AMD GPU is what I added above by hres = DXGIFactory6->EnumAdapterByGpuPreference( adapterNo, DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE, IID_PPV_ARGS( &pAdapter ) );

The DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE test exactly for this and I found it in the GPUOpen samples.

Comment (SRSaunders) [reply neo/sys/DeviceManager_DX12.cpp:277]: Yes, I had already looked at the docs for `EnumAdapterByGpuPreference(... DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE ...)` and the function returns a GPU using the order of preference, but _does not indicate the type of GPU actually found_.  For instance, if you have only one GPU in your system and it is an iGPU, it will return success on the first call when using `DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE`. Conversely if you make the call using `DXGI_GPU_PREFERENCE_MINIMUM_POWER` and have only one dGPU in your system, it will return success on the first call as well.  Unfortunately it gives no indication of the choice it made, and you have to guess using heuristics.  I looked up this problem on Stack Overflow and no one seems to have a good solution other than using `DedicatedVideoMemory ` as a possible classifier.  Fortunately, in RBDoom3BFG this is only for classification of the chosen GPU, and not for setting order of preference.

At this point no DX12 rendering code uses `glConfig.gpuType`, however I wanted to make sure it was not undefined in case this was needed in the future.  This was my best guess.  If you have a better idea please let me know.

Comment (RobertBeckebans) [reply neo/sys/DeviceManager_DX12.cpp:277]: You are right. The flag just helps to pick the better GPU if there are multiple GPUs like in my AMD laptop.

Comment (SRSaunders) [reply neo/sys/DeviceManager_DX12.cpp:277]: Thanks @RobertBeckebans for merging.  However, I am interested in validating the iGPU memory threshold for an AMD APU.  I tested on Intel but don't have an AMD processor.  Can you tell me the amount of `aDesc.DedicatedVideoMemory` if you force selection of your iGPU on your laptop?

Comment (RobertBeckebans) [reply neo/sys/DeviceManager_DX12.cpp:277]: m_RendererString = "AMD Radeon RX 6600M" <-- dedicated GPU
aDesc.DedicatedVideoMemory = 8523649024

m_RendererString = "AMD Radeon(TM) Graphics"
aDesc.DedicatedVideoMemory = 2130460672

Comment (SRSaunders) [reply neo/sys/DeviceManager_DX12.cpp:277]: Interesting.  I had read somewhere that AMD internal GPUs could dedicate 2 GB as Video Memory, but did not have any hard evidence until your feedback here.  I guess that means:

`glConfig.gpuType = aDesc.DedicatedVideoMemory > 0x20000000 ? GPU_TYPE_DISCRETE : GPU_TYPE_OTHER;`

should really be:

`glConfig.gpuType = aDesc.DedicatedVideoMemory > 0x80000000 ? GPU_TYPE_DISCRETE : GPU_TYPE_OTHER;`

In today's world, I don't know of any dedicated GPU with 2 GB of video memory, so we should be safe with this higher threshold fir iGPUs.  I can add this small change to my coming PR for the new Vulkan SDK.  Please let me know if this would be ok with you.

Comment (SRSaunders) [reply neo/sys/DeviceManager_DX12.cpp:277]: I’ve decided to leave it as is for now.  My son’s AMD 9700X desktop has a Radeon Graphics iGPU with 512M dedicated memory, so I was not far off.  I’d like to know @RobertBeckebans AMD laptop processor type before changing the threshold.  Closing this thread for now.
